Positive Tests for Rest Countries
miaunescu/TestFrameworkCSharp pull request #6
Opened 2023-04-20 07:39 UTC by virgildimitriu

Test 1 - Get the Country by diff properties like name, region, subregion etc. 
Test 2 - Check the latitude and longitude are in the expected ranges 
Test 3 - Check that continent is in the list of expected continents

2023-04-20 14:28 UTC, miaunescu requested changes
Mainly the troubles are related to not checking nulls on complex objects before asserting information from inside. It is a good habit to do that, because you avoid exceptions that can pot tests in uncertain states.

2023-04-20 14:28 UTC, miaunescu commented on TestFrame/Tests/CountriesTests/CountriesTest.cs
> +                getResponse[0].Name.Common.Should().Be(nameCountry.Common);
Please add a null check for Name before checking the Common, otherwise, it can throw an exception

2023-04-20 14:28 UTC, miaunescu commented on TestFrame/Tests/CountriesTests/CountriesTest.cs
> +                getResponse[0].Maps.GoogleMaps.Should().Be(mapsCountry.GoogleMaps);
Same here

2023-04-21 09:21 UTC, virgildimitriu commented on TestFrame/Tests/CountriesTests/CountriesTest.cs
> +                getResponse[0].Maps.GoogleMaps.Should().Be(mapsCountry.GoogleMaps);
Updated based on the comments. Please review again

2023-04-21 09:22 UTC, virgildimitriu commented on TestFrame/Tests/CountriesTests/CountriesTest.cs
> +                getResponse[0].Name.Common.Should().Be(nameCountry.Common);
Updated based on the comments. Please review again

2023-04-21 10:50 UTC, miaunescu approved these changes

2023-04-21 10:50 UTC, merged