added tests for CatNinja
miaunescu/TestFrameworkCSharp pull request #7
Opened 2023-04-20 10:54 UTC by AndreeaMonica

2023-04-20 12:40 UTC, AlexSpinu requested changes
Fa i te rog si merge cu main-ul actual

2023-04-21 11:33 UTC, miaunescu requested changes

2023-04-21 11:33 UTC, miaunescu commented on TestFrame/Tests/CatsTests/CatFactsTests.cs
> +                getResponse.Data.ElementAt(0).Breed.Should().Be("Abyssinian");
please check for nulls at different levels, Data, Elements.

2023-04-21 11:33 UTC, miaunescu commented on TestFrame/Tests/CatsTests/CatFactsTests.cs
> -                getResponse.Data.ElementAt(0).Breed.Should().Be("Abyssinian");
same here

2023-04-21 11:33 UTC, miaunescu commented on TestFrame/Tests/CatsTests/CatFactsTests.cs
> +                getResponse.PerPage.Should().Be($"{10}");
GetResponse could still be null here

2023-04-26 06:42 UTC, miaunescu approved these changes

2023-04-26 06:42 UTC, merged